package scrabblebot;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'colinmcenearney' at '1/6/15 1:55 PM' with Gradle 2.2.1
 *
 * @author colinmcenearney, @date 1/6/15 1:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
